### PR TITLE
Chore/update team permissions

### PR DESCRIPTION
**Pull request by jpower432**
Fills out some initial ideas for teams for code review delegation.

### CODE REVIEW

**Comment by afflom** [comment]
I've been meaning to ask, is there a peribolos command line validator?

**Review by afflom — APPROVED** [review]
Hard to tell if this is valid. I compared it to the sample config from the peribolos upstream and checked it for indentation. LGTM from what I can tell.

**Comment by jpower432** [comment]
> I've been meaning to ask, is there a peribolos command line validator?

It looks like Knative has a python [script](https://github.com/knative/community/blob/main/peribolos/validate-schema.py).

**Review by usrbinkat — APPROVED** [review]
lgtm

**Pull request merged**
